name: nf-core-clinvap-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - pkgs/r
dependencies:
  # TODO nf-core: Add required software dependencies here
  - ensembl-vep=95.3
  - r-dplyr=0.7.6
  - r-tidyr=0.8.1
  - r-stringr=1.3.1
  - r-readr=1.1.1
  - r-rcurl=1.95_4.11
  - r-devtools=1.13.6
  - r-optparse=1.3.2
  - r-log4r=0.2
  - r-futile.logger=1.4.3
  - r-fs=1.2.6