# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-clinvap-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - sbilge
dependencies:
  - conda-forge::r-markdown=1.1
  - bioconda::ensembl-vep=95.3
  - r::r-dplyr=0.7.6
  - r::r-tidyr=0.8.1
  - r::r-stringr=1.3.1
  - conda-forge::r-readr=1.3.1
  - r::r-rcurl=1.95_4.11
  - r::r-devtools=1.13.6
  - conda-forge::r-optparse=1.6.0
  - conda-forge::r-log4r=0.2
  - conda-forge::r-futile.logger=1.4.3
  - conda-forge::r-fs=1.2.7
  - conda-forge::perl=5.26.2
  - conda-forge::make=4.2.1
  - bioconda::perl-archive-zip=1.64
  - bioconda::perl-dbd-mysql=4.046
  - bioconda::perl-dbi=1.642
  - conda-forge::c-compiler=1.0.4
  - conda-forge::zlib=1.2.11
  - bioconda::htslib=1.10.2
  - bioconda::perl-bio-db-hts=3.01
  - bioconda::perl-bioperl=1.7.2
  - sbilge::r-tidyjson 
  - bioconda::bioconductor-variantannotation=1.32.0
  - conda-forge::r-dtplyr=1.0.1
