# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-clinvap-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - sbilge
dependencies:
  - conda-forge::r-markdown
  - r::r-base=3.6
  - conda-forge::r-vctrs
  - bioconda::ensembl-vep
  - conda-forge::r-rlang
  - r::r-dplyr
  - r::r-tidyr
  - r::r-stringr
  - r::r-tibble
  - conda-forge::r-readr
  - r::r-rcurl
  - r::r-devtools
  - conda-forge::r-mime
  - conda-forge::r-getopt
  - conda-forge::r-optparse
  - conda-forge::r-log4r
  - conda-forge::r-futile.logger
  - conda-forge::r-fs
  - conda-forge::perl
  - conda-forge::make
  - bioconda::perl-archive-zip
  - bioconda::perl-dbd-mysql
  - bioconda::perl-dbi
  - conda-forge::c-compiler
  - conda-forge::zlib
  - bioconda::htslib
  - bioconda::perl-bio-db-hts
  - bioconda::perl-bioperl
  - sbilge::r-tidyjson 
  - bioconda::bioconductor-variantannotation
