# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-clinvap-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - sbilge
dependencies:
  - conda-forge::r-markdown=1.1
  - r::r-base=3.6
  - conda-forge::r-vctrs=0.2.3
  - bioconda::ensembl-vep=95.3
  - conda-forge::r-rlang=0.4.0
  - r::r-dplyr=0.8.0
  - r::r-tidyr=0.8.1
  - r::r-stringr=1.4.0
  - r::r-tibble=2.1.1
  - conda-forge::r-readr=1.3.1
  - r::r-rcurl=1.95_4.12
  - r::r-devtools=2.0.2
  - conda-forge::r-mime=0.9
  - conda-forge::r-getopt=1.20.3
  - conda-forge::r-optparse=1.6.4
  - conda-forge::r-log4r=0.2
  - conda-forge::r-futile.logger=1.4.3
  - conda-forge::r-fs=1.3.1
  - conda-forge::perl=5.26.2
  - conda-forge::make=4.2.1
  - bioconda::perl-archive-zip=1.64
  - bioconda::perl-dbd-mysql=4.046
  - bioconda::perl-dbi=1.642
  - conda-forge::c-compiler
  - conda-forge::zlib
  - bioconda::htslib
  - bioconda::perl-bio-db-hts
  - bioconda::perl-bioperl
  - sbilge::r-tidyjson 
  - bioconda::bioconductor-variantannotation=1.32.0
